name: Deploy Infra via Pulumi

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente / stack base"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login Azure
      uses: azure/login@v1
      with:
        auth-type: SERVICE_PRINCIPAL
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install sqlcmd
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

    - name: Pulumi Up
      uses: pulumi/actions@v4
      with:
        command: up
        stack-name: RenatoDidierFernandes/KeepImprovingProject/${{ inputs.environment }}-${{ github.ref_name }}
        work-dir: deploy

    - name: Export Pulumi Outputs
      run: |
        echo "SQL_SERVER=$(pulumi stack output sqlServerName)" >> $GITHUB_ENV
        echo "SQL_DATABASE=$(pulumi stack output sqlDatabaseName)" >> $GITHUB_ENV

    - name: SQL Bootstrap (AAD)
      run: |
        sqlcmd \
          -S $SQL_SERVER.database.windows.net \
          -d $SQL_DATABASE \
          -G \
          -Q "
            IF NOT EXISTS (
              SELECT 1 FROM sys.database_principals
              WHERE name = 'uami-keepimprovingproject-${{ inputs.environment }}'
            )
            BEGIN
              CREATE USER [uami-keepimprovingproject-${{ inputs.environment }}] FROM EXTERNAL PROVIDER;
              ALTER ROLE db_datareader ADD MEMBER [uami-keepimprovingproject-${{ inputs.environment }}];
              ALTER ROLE db_datawriter ADD MEMBER [uami-keepimprovingproject-${{ inputs.environment }}];
            END
          "
